# Generated by Django 5.0.6 on 2024-06-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
